---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ubuntu
    image: ubuntu:xenial
    groups:
      - compile
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      compile:
        pyenv_python_versions:
          3.6.0
scenario:
  name: compile
verifier:
  name: testinfra
  lint:
    name: flake8
