---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: bionic
    image: ubuntu:bionic
    groups:
      - compile
provisioner:
  name: ansible
  inventory:
    group_vars:
      compile:
        pyenv_python_versions: 3.9.0
scenario:
  name: compile
verifier:
  name: testinfra
